### PR TITLE
Having a new with param to indicate that the where expression is immutable

### PR DESCRIPTION
**Pull request by CedricCouton**
In order to avoir the update of index that are not concerned by its where clause when this one is immutable I proposed to have a new WITH param. This new param can be "where_expr_immutable"

### CODE REVIEW

**Comment by deepkaran** [comment]
Thanks @CedricCouton for the PR. The existing "Immutable" flag in the IndexDefn was for the purpose of indicating if the where expression is immutable or not. It was disabled in 7.0 due to https://issues.couchbase.com/browse/MB-37737 and the fix was backported to 6.5.1. 

The recommended approach is to enable bloom filter which helps with the following scenarios: 
1. Partial Indexes - Back-index lookups.
2. New Index inserts - Back-index lookups not required to delete old index entry from back-index.
3. Delete/expiry for partitioned index - The delete saves on the back-index lookup for all partitions.

With CB Server 7.1, the memory resident requirement for indexes have been reduced from 20% to 10%. It is a reasonable trade-off to enable bloom filter(and its associated overhead) as compared to the savings of back-index lookups.

**Comment by CedricCouton** [comment]
Thanks @deepkaran for your answer. I didn't see this "Immutable" ^^. How can be sure that the bloomFilter is really used other than the checked option in the UI? Is there a monitoring data? Or just to check the read OPS on the node?

**Comment by deepkaran** [comment]
@CedricCouton , bloom filter stats are published on the storage stats REST endpoint for every index (http://<indexer_node_ip>:9102/stats/storage). You can check the following stats for BackStore:

a. "memory_size_bloom_filter" - memory size of bloom filter
b. "bloom_tests" - number of bloom filter tests
c. "bloom_false_positives" - number of false positives
d. "bloom_fp_rate" - false positive rate
e. "bloom_negatives" - negatives

**Comment by CedricCouton** [comment]
Thanks @deepkaran

**Pull request closed without merging**
